name: "Synopsys Intelligent Security Scan"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security:
    name: security scans
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run Synopsys Detect
      uses: synopsys-sig/detect-action@v0.3.4
      with:
          scan-mode: RAPID
          detect-blackduck-rapid-compare-mode: BOM_COMPARE_STRICT
          project-name: hyperwallet-program-portal
          project-version-name: 1.0.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          cleanup: false
      env:
          #DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE_STRICT      
          #DETECT_PROJECT_GROUP_NAME: PayPalBU-Venmo
          LOGGING_PROJECT_GROUP_NAME: DEBUG
          LOGGING_LEVEL_COM_SYNOPSYS_INTEGRATION: DEBUG
          #DETECT_PROJECT_USER_GROUPS: PP_SSO_BLACKDUCK_USER,PP_SSO_BLACKDUCK_ADMIN,PP_SSO_BLACKDUCK_SECURITY_CHAMPION
          DETECT_DETECTOR_SEARCH_CONTINUE: TRUE #Will search all subdirectories for build files
          DETECT_POLICY_CHECK_FAIL_ON_SEVERITIES: BLOCKER,CRITICAL #This will fail the scan only if BLOCKERS and CRITICALS
          DETECT_EXCLUDED_DIRECTORIES: "'DevRunner,*Test*,*test*,*mock*,build,docs,spec,docker,config,tasks,*locale*,*Locale*,*Content*,*content*,public,templates,documentation,*temp*,*tmp*,.repository,.github,.git'" #Exclude these dirs from the scan
          DETECT_PARALLEL_PROCESSORS: 0
          DETECT_PROJECT_NAME: hyperwallet-program-portal
          DETECT_PROJECT_VERSION_NAME: 1.0.0
